### ISSUE TITLE
align value after the :

### ISSUE THREAD

**Issue by ghost** [wbond/sublime_alignment#27]
When I write CSS, I usually don't align like

``` css
body {
  background-color: black;
  color           : white;
}
```

but like

``` css
body {
  background-color: black;
  color:            white;
}
```

It would be great if Alignment could support this too.
