### ISSUE TITLE
YAML : Aligment should align values instead of keys

### ISSUE THREAD

**Issue by gdlx** [wbond/sublime_alignment#29]
Hi,

When using alignment on a yaml file, it aligns keys. Exemple :

On this block :

```
en:
  errors:
    messages:
      blank: "This should not be blank"
      invalid: "There's invalid characters"
```

Alignment does this :

```
      en:
      errors:
      messages:
      blank: "This should not be blank"
      invalid: "There's invalid characters"
```

I think it should do this :

```
en:
  errors:
    messages:
      blank:   "This should not be blank"
      invalid: "There's invalid characters"
```

**Comment by leifcr** [comment]
You can achieve this by creating a file YAML.sublime-settings in the alignment package folder.
Content:

``` JSON
{
    "alignment_chars": ["\"", "'"],
    "alignment_space_chars": ["\"", "'"]
}
```

However, this won't work for YAML where you don't have either ' or "
For instance this yaml won't align properly with the above settings, as the number won't get recognized.

``` YAML
cow:
  number: 5
  name: "donkey"
```
